version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  etcd:
    image: elcolio/etcd
    ports:
      - "9379:2379"
      - "10001:4001"

  jss:
    build: .
    ports:
      - "9443:8443"
      - "9080:8080"
    links:
      - mysql:db
      - etcd
    depends_on:
      - mysql
      - etcd

volumes:
  db-data:
    driver: local
